### ISSUE TITLE
Can't use imagine_settings command

### ISSUE THREAD

**Issue by hobolyra** [ellypaws/sd-discord-bot#4]
Not sure if I just built the code wrong, but the bot generates just fine and connects, but none of the settings options work. Throws the error:
`ERROR: Could not run the [command](https://github.com/ellypaws/sd-discord-bot) `imagine_settings``

it ill even put a similar error when using imagine, but still generate the images just fine:
`ERROR: Could not run the [command](https://github.com/ellypaws/sd-discord-bot) `imagine``

For settings, in discord the bot just gets stuck on the "thinking" message, but you can't remove that message or dismiss it.

**Comment by ellypaws** [comment]
Hello!

Make sure you're building from the latest commit. One of the problems with imagine_settings previously was a bug in discordgo in regards to ComponentEmojis

https://github.com/ellypaws/stable-diffusion-discord-bot/pull/2

This was fixed in the very last commit https://github.com/ellypaws/sd-discord-bot/commit/cc27d625ec61d51af23cf443a4201495ad4e6490. I’ve tried it out on my end and it still seems to work out for me.

I added back in a missing commit just now that adds a bit of logging, so you could recompile and see a bit more info on what the error might be when you run those commands.

Thanks!

**Comment by hobolyra** [comment]
> Hello!
> 
> Make sure you're building from the latest commit. One of the problems with imagine_settings previously was a bug in discordgo in regards to ComponentEmojis
> 
> [ellypaws/stable-diffusion-discord-bot#2](https://github.com/ellypaws/stable-diffusion-discord-bot/pull/2)
> 
> This was fixed in the very last commit [cc27d62](https://github.com/ellypaws/sd-discord-bot/commit/cc27d625ec61d51af23cf443a4201495ad4e6490). I’ve tried it out on my end and it still seems to work out for me.
> 
> I added back in a missing commit just now that adds a bit of logging, so you could recompile and see a bit more info on what the error might be when you run those commands.
> 
> Thanks!

Are there any compile commandline options you recomend, or is the general Go build just fine?

**Comment by ellypaws** [comment]
Because the sqlite library included is a CGO free port, the default build works just fine. I've only been programming less than a year so I've even have less experience with releases but I may compile one later.

Before building, make sure you run (assuming you're in the same directory) `go mod tidy` to fetch all the libraries from go.mod

**Comment by hobolyra** [comment]
Awesome, new update worked perfectly. Thank you for all of your work on this!
